// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000059)
Ads_Build='00000059';var QQbA,QQcA,QQdA,QQeA,QQfA,QQgA,QQhA,QQiA,QQjA,QQkA,QQlA,QQmA,QQnA,QQoA,QQpA;NUM_FARM=1;QQbA=['http://a.as-test.falkag.net' ,'http://a.as-eu.falkag.net' ,'http://a.ads.t-online.de' ,'http://a.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQcA=['http://a.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQdA=['http://a.as-test.falkag.net' ,'http://a.as-eu.falkag.net' ,'http://a.ads.t-online.de' ,'http://a.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQeA=['http://a.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQfA=['http://bw.as-test.falkag.net' ,'http://bw.as-eu.falkag.net' ,'http://bw.ads.t-online.de' ,'http://bw.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQgA=['http://bw.as-test.falkag.net' ,'https://s.as-eu.falkag.net' ,'https://s.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://a.as-rh4.falkag.net' ,'','','','',''];QQhA=['http://red.as-test.falkag.net' ,'http://red.as-eu.falkag.net' ,'http://red.ads.t-online.de' ,'http://red.as-us.falkag.net' ,'http://red.as-rh4.falkag.net' ,'','','','',''];QQiA=['http://red.as-test.falkag.net' ,'https://red.as-eu.falkag.net' ,'https://red.ads.t-online.de' ,'https://s.as-us.falkag.net' ,'http://red.as-rh4.falkag.net' ,'','','','',''];QQjA=['http://sel.as-test.falkag.net/server/asldata.js','http://data.as-eu.falkag.net/server/asldata.js','http://data.ads.t-online.de/server/asldata.js' ,'http://data.as-us.falkag.net/server/asldata.js' ,'http://a.as-rh4.falkag.net/server/asldata.js','','','','',''];QQkA=['http://sel.as-test.falkag.net/server/asldata.js','https://as1.falkag.de/server/asldata.js' ,'https://red.ads.t-online.de/server/asldata.js' ,'https://s.as-us.falkag.net/server/asldata.js' ,'http://a.as-rh4.falkag.net/server/asldata.js','','','','',''];QQlA=['.as-test.falkag.net' ,'.as-eu.falkag.net' ,'.ads.t-online.de' ,'.as-us.falkag.net' ,'.as-rh4.falkag.net' ,'','','','',''];QQmA=['Falk AdSolution' ,'AdSolution' ,'Adsolution' ,'Falk AdSolution' ,'Falk AdSolution RH4' ,'','','','',''];QQnA=['/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'/dat/bgf/trpix.gif?' ,'','','','',''];QQoA=['/red?cmd=red&' ,'/red?cmd=red&' ,'/red?cmd=red&' ,'/red?cmd=red&' ,'/red?cmd=red&' ,'','','','',''];QQpA=['/red?cmd=url&' ,'/red?cmd=url&' ,'/red?cmd=url&' ,'/red?cmd=url&' ,'/red?cmd=url&' ,'','','','',''];// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000059)
function QQbD(QQRb)
{document.write('<scr'+'ipt type="text/javascript" language="JavaScript" src="'+QQRb+'"></scr'+'ipt>');}function QQcD(QQSb)
{var QQTb=this.location.hostname.toLowerCase();var QQUb='';var QQVb=QQTb;var QQWb=[];intPos1=QQTb.indexOf('.');if (QQSb==1)
{if (intPos1!=-1)
{while (intPos1!=-1)
{intPos1=QQVb.indexOf('.');QQWb[QQWb.length]=(intPos1==-1)?QQVb.substring(intPos1+1,QQVb.length):QQVb.substring(0,intPos1);QQVb=QQVb.substring(intPos1+1,QQVb.length);}if (QQWb[QQWb.length-2]=='falkag')
{for (var intI=1;intI<QQWb.length;intI++)
{QQl=QQWb.length-intI;QQUb=QQWb[QQl]+((QQUb=='')?'':'.'+QQUb);}}else
{QQUb=(QQWb[QQWb.length-2].length<3)?QQTb:QQWb[QQWb.length-2]+'.'+QQWb[QQWb.length-1];}}}else
{if (intPos1==-1)
{QQUb='';}else
{if((intPos1>=0)&&(intPos1<QQTb.length))
{intPos2=QQTb.indexOf('.',intPos1+1);if(intPos2>intPos1)
QQUb=QQTb.substring(intPos1+1,QQTb.length);}if ((QQUb.lastIndexOf('.')==QQUb.indexOf('.'))&&QQUb.lastIndexOf('.')<3)
QQUb=QQTb;}}return QQUb;}function QQdD()
{var QQUb=QQcD(0);if(QQUb=='')
return 'D'+this.location.hostname;else
return 'D'+QQUb;}function QQeD(QQXb)
{var QQUb=QQcD(0);if(QQXb==-1)
{	 if(QQUb!='')
	 QQUb=' domain='+QQUb;	return ';path=/;'+QQUb;}var QQYb=new Date();if(QQUb!='')
QQUb=';domain='+QQUb;QQYb.setTime(parseInt(QQYb.getTime(),10)+1000*60*parseInt(QQXb,10));return ';path=/;expires='+QQYb.toGMTString()+QQUb;}function QQfD(QQXb)
{var QQUb=QQcD(1);if(QQXb==-1)
{	 if(QQUb!='')
	 QQUb=' domain='+QQUb;	return ';path=/;'+QQUb;}var QQYb=new Date();if(QQUb!='')
QQUb=';domain='+QQUb;QQYb.setTime(parseInt(QQYb.getTime(),10)+1000*60*parseInt(QQXb,10));return ';path=/;expires='+QQYb.toGMTString()+QQUb;}function QQgD(QQc,QQd,QQy)
{if(QQsA!=-1) var intBwdTyp=KAS[QQsA][4][27];if(typeof(intBwdTyp)=='undefined')
intBwdTyp=0;var QQz=[];QQz[0]='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd+'&kid='+QQc+QQy[0]+((QQyC( Ads_iid,QQc )&&(QQvB>0))?QQtB:'');QQz[1]='&dlv='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd+'&kid='+QQc+'&chw='+QQqA+'&tcs='+QQrA+QQy[1]+((QQyC( Ads_iid,QQc )&&(QQvB>0))?QQtB:'')+QQvA;var QQZb='&sta=';QQz[0]+='&dmn='+Ads_T[5];QQz[1]+='&dmn='+Ads_T[5];if(navigator.appVersion.substring(0,1)>'3')
{QQz[0]+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;QQz[1]+='&scx='+screen.width+'&scy='+screen.height+'&scc='+screen.colorDepth;QQZb+=',,,'+(navigator.javaEnabled()?'1':'0');if(navigator.javaEnabled())
QQz[1]+='&jav=1';}else
QQZb+=',,,';var QQAc=new Date();QQZb+=',,,,,,';if((Ads_wrd!='')&&(Ads_wrd.toLowerCase()!='[keyword]'))
{var QQBc='!"%&\'()*+#-./:;<=>?@[\\]^{|}~§ ';var QQCc,QQDc='';for(QQl=0;QQl<Ads_wrd.length;QQl++)
{QQCc=Ads_wrd.charAt(QQl);if(QQBc.indexOf(QQCc)!=-1)
QQCc=',';QQDc+=QQCc;}QQDc =QQDc.toLowerCase();QQz[0]+='&wrd='+QQDc;QQz[1]+='&wrd='+QQDc;Ads_wrd=QQDc;QQZb+='';}QQZb+=','+QQwE[10]+','+Ads_T[13]+','+intBwdTyp+','+Ads_T[4]+','+Ads_T[10]+','+Ads_T[11]+','+Ads_T[3]+','+Ads_T[12];QQz[0]+=QQZb;QQz[1]+=QQZb;if(gbolSUXX25067) QQz[1]+='&trglog='+escape(gstrXarrTargetDaten);QQz[0]=Ads_Timestamp+QQz[0];QQz[1]=Ads_Timestamp+QQz[1];QQz[2]=QQz[1]+QQy[0];return (QQz);}function QQhD(QQc,QQd,QQy)
{var QQEc=[];var QQFc=[];QQFc=QQgD(QQc,QQd,QQy);QQEc[0] ='&rdm='+QQFc[0]+'&iid='+Ads_iid+'&bid='+QQd;QQEc[1] ='&rdm='+QQFc[1]+'&iid='+Ads_iid+'&bid='+QQd;return QQEc;}function QQiD()
{if (typeof(QQgB[Ads_sec])=='undefined')
QQuC();return QQgB[Ads_sec]+(QQyA?QQoA[NUM_FARM]+'flg='+QQxC()+'&dat='+QQfB[Ads_sec]+'/dat/bgf/trpix.gif&':QQnA[NUM_FARM]);}function QQjD()
{return QQgB[Ads_sec]+QQnA[NUM_FARM]+'cmd=req&';}function QQkD(QQGc,QQb)
{if (QQGc==0)
{QQpD(1,'',QQiD()+QQb);return ((Ads_opt&512)>0)?'':(QQtD('Ads_Count'+Ads_iid)+'<img src="'+QQiD()+QQb+'" width="1" height="1">'+QQuD());}else if (QQGc==1)
{QQpD(1,'Request tracking URL',QQjD()+QQb);return QQtD('Ads_ReqCount'+Ads_iid)+'<img src="'+QQjD()+QQb+'" width="1" height="1">'+QQuD();}}function QQlD(QQt,QQb)
{QQt.document.write(QQkD(0,QQb));}function QQmD()
{return QQnD(Math.random()*100000000,8);}function QQnD(QQHc,QQIc)
{var QQJc='#'+(QQHc+100000000);return QQJc.substr(10-QQIc,QQIc);}function QQoD(QQDc,QQKc,QQLc)
{var QQl;while((QQl=QQDc.indexOf(QQKc))!=-1)
QQDc=QQDc.substr(0,QQl)+QQLc+QQDc.substring(QQl+QQKc.length,QQDc.length);return QQDc;}function QQpD(QQD,QQDc,QQMc)
{var QQNc=new Date();if(Ads_debug==1)
{document.write(((QQD!=3)?'':'<br>')+'<font color=#0000ff>[DEBUG'+((QQNc-QQwA)/1000)+']</font> ');if((QQD==0)||(QQD==3))
document.write('<b><big>'+QQDc+'</big></b><br>');else if(QQD==1)
document.write(''+QQDc+': &nbsp;<font color=#000080>'+QQMc+'</font><br>');else
document.write('<b>'+QQDc+'</b><br>');}else if((Ads_debug==2)&&(QQD==3))
document.write('<font color=#0000ff>[DEBUG'+((QQNc-QQwA)/1000)+']</font> <b><big>'+QQDc+'</big></b><br>');}function QQqD(QQAb)
{var QQC='#'+(parseInt(QQAb,10)+100000000);return QQC.substr(2,2)+'/'+QQC.substr(4,2)+'/'+QQC.substr(6,2)+'/'+QQC.substr(8,2);}function QQrD(QQHc)
{var QQOc='0123456789ABCDEF';var QQPc='';while(QQHc>0)
{QQPc=QQOc.substr(QQHc%16,1)+QQPc;QQHc=parseInt(QQHc/16,10);}return (QQPc=='')?'0':QQPc;}function QQsD(QQKa)
{var QQQc;var QQRc=0;if(QQaB>-1)
{QQRc=QQaB;return QQRc;}if((QQKa==0)&&((Ads_opt&2048)>0))
return -1;if((navigator.userAgent.indexOf("Opera")!=-1)||((navigator.appName=="Netscape")&&(navigator.userAgent.indexOf("Mozilla")!=-1)&&(parseFloat(navigator.appVersion)>=4)))
{if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)
{QQQc=navigator.plugins['Shockwave Flash'].description;QQQc=QQQc.substring(QQQc.indexOf("."),-1);QQRc=QQQc.substr(-1);}}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Mac")!=-1&&document.all)
{if(navigator.mimeTypes&&navigator.mimeTypes["application/x-shockwave-flash"]&&navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin)
{QQQc=navigator.plugins['Shockwave Flash'].description;QQQc=QQQc.substring(QQQc.indexOf("."),-1);QQQc=QQQc.substring(QQQc.length-1,QQQc.length);QQRc=QQQc.substr(-1);}}else if(navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1&&navigator.userAgent.indexOf("Windows")!=-1&&navigator.userAgent.indexOf("Windows 3")==-1&&document.all)
{document.write('<scr'+'ipt language=VBScript>\n Ads_vbCV=10\nAds_vbMV=1\nDo\nOn Error Resume Next\n');document.write('Ads_vbBF=(IsObject(CreateObject("ShockwaveFlash.ShockwaveFlash."&Ads_vbCV)))\n');document.write('If Ads_vbBF=true Then Exit Do\nAds_vbCV=Ads_vbCV-1\nLoop While Ads_vbCV>=Ads_vbMV\n </scr'+'ipt>');QQRc=Ads_vbCV;}QQaB=QQRc;return QQRc;}function QQtD(QQSc)
{if(QQrB)
return '<div id='+QQSc+' style="position:absolute;left:-1000;top:-1000;">';else
return '';}function QQuD()
{if(QQrB)
return '</div>';else
return '';}function QQvD(QQTc)
{var QQUc,QQVc;if(window.innerHeight)
{QQUc=QQTc.x;QQVc=QQTc.y;}else
{if(QQTc.offsetLeft)
{QQTc=QQTc;QQUc=QQTc.offsetLeft;QQQj=QQTc.offsetParent;while(QQQj!=null)
{QQUc+=QQQj.offsetLeft;QQQj=QQQj.offsetParent;}QQVc=QQTc.offsetTop;QQQj=QQTc.offsetParent;while(QQQj!=null)
{QQVc+=QQQj.offsetTop;QQQj=QQQj.offsetParent;}}else
return [-1000,-1000];}return [QQUc,QQVc];}function QQwD(QQWc,QQA,QQf,QQg)
{var QQXc;var QQTc=document.images[QQA];var QQYc=QQvD(QQTc);QQTc.width=QQf;QQTc.height=QQg;if(QQrB)
QQXc=document.getElementById(QQWc).style;else if(document.layers)
QQXc=document.layers[QQWc];else
QQXc=document.all[QQWc].style;QQXc.left=QQYc[0];QQXc.top=QQYc[1];if (QQrB) QQXc.display='block';else if(document.layers) QQXc.visibility='show';else QQXc.visibility='visible';}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000059)
if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=QQwC;gbolSUXX25067=false;var Ads_ModulMain=true;if(typeof(Ads_ModulEffects)=='undefined')
Ads_ModulEffects=false;var QQqA,QQrA,QQsA,QQtA,QQuA,QQvA,QQwA,QQxA;var QQyA,QQzA,QQaB,QQbB,QQcB,QQdB;var QQeB=false;var QQfB=[];var QQgB=[];var QQhB=[];var QQiB=[];var QQjB=[];var QQkB=[];var QQlB=[];var QQmB=navigator.userAgent.toLowerCase();var QQnB=(QQmB.indexOf("msie")!=-1);var QQoB=((QQmB.indexOf("win")!=-1)||(QQmB.indexOf("16bit")!=-1));var QQpB=(QQmB.indexOf("mac")!=-1);var QQqB=(navigator.appName.indexOf('icrosoft')!=-1);var QQrB=(typeof(document.getElementsByTagName)!='undefined'&&typeof(document.createElement)!='undefined')?1:0;var QQsB=true;var QQtB='';var QQuB='';var QQvB=0;var QQwB=[];var QQxB=0;var QQyB=0;var QQzB=[];var QQaC;var QQbC=[];var QQcC=[];var QQdC=[];var QQeC=[];var QQfC=[];var QQgC=[];var QQhC=[];var QQiC=[];var Ads_LinkUrl,Ads_CountUrl,Ads_CountUrl_ne,Ads_ClickUrl,Ads_T,Ads_T_OW,iid,bid,rdm;var Ads_Data=[];if(typeof(Ads_FXPL)=='undefined'){var Ads_FXPL=false;}Ads_T_OW=[];var QQjC,QQkC,Ads_gintCurVersion;var QQlC='toolbar=yes,directories=yes,status=yes,scrollbars=yes,resizable=yes,menubar=yes,location=yes';function gotoSite(){window.open(QQjC,'flashwin',QQlC);}function emosite(){window.open(QQjC,'flashwin',QQlC);}function FlashClick(){window.open(QQjC,'flashwin',QQlC);}function link1(){window.open(QQjC,'flashwin',QQlC);}function gotoURL(QQa){window.open(QQkC+escape(QQa),'flashwin',QQlC);}function QQmC()
{Ads_kid=0;Ads_bid=0;Ads_cmd='';}function QQnC(QQa)
{QQa=QQoD(QQa,'[par]',escape(Ads_par));QQa=QQoD(QQa,'[keyword]',escape(Ads_wrd));QQa=QQoD(QQa,'[timestamp]',Ads_Timestamp);if (typeof(Ads_CountUrl)!='undefined')
{QQa=QQoD(QQa,'[clickurl]',escape(Ads_CountUrl));QQa=QQoD(QQa,'[clickurl_plain]',Ads_CountUrl);QQa=QQoD(QQa,'[clickurl_double]',escape(escape(Ads_CountUrl)));QQa=QQoD(QQa,'[clickurl_ne]',escape(Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne='));QQa=QQoD(QQa,'[clickurl_plain_ne]',Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=');QQa=QQoD(QQa,'[clickurl_double_ne]',escape(escape(Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=')));}QQa=QQoD(QQa,'[web_id]',Ads_wid);QQa=QQoD(QQa,'[web_external_id]',escape(Ads_xwid));QQa=QQoD(QQa,'[con_id]',Ads_iid);QQa=QQoD(QQa,'[con_external_id]',escape(Ads_xiid));QQa=QQoD(QQa,'[ban_id]',Ads_sbid);QQa=QQoD(QQa,'[cam_id]',QQtA);return QQa;}function QQoC(QQa,QQb)
{QQpD(1,'QQoC QQb',QQb);return QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQxC()+'&'+QQb+'&dat='+escape(QQa);}function QQpC(QQc,QQd,QQe,QQf,QQg)
{var QQh;if(QQvB<2)
{QQvB++;QQh=QQvB+1;QQtB+='&kid'+QQh+'='+QQc;QQtB+='&bid'+QQh+'='+QQd;QQtB+='&iid'+QQh+'='+Ads_iid;QQtB+='&dlv'+QQh+'='+Ads_nid+','+Ads_wid+','+Ads_iid+','+QQc+','+QQd;if(QQuA!=0)
QQtB+='&sid'+QQh+'='+QQuA;QQtB+='&bls3'+QQh+'='+QQuB;arrIntern=QQaD(QQe);QQxB=arrIntern[1];QQyB=arrIntern[2];Ads_iid=arrIntern[1];Ads_kid=arrIntern[2];Ads_bid=(arrIntern.length<4)?0:arrIntern[3];Ads_par=(arrIntern.length<5)?Ads_par:unescape(arrIntern[4]);Ads_xp=(arrIntern.length<6||Ads_xp!='')?Ads_xp:arrIntern[5];Ads_yp=(arrIntern.length<7||Ads_yp!='')?Ads_yp:arrIntern[6];Ads_xp1=(arrIntern.length<8||Ads_xp1!='')?Ads_xp1:arrIntern[7];Ads_yp1=(arrIntern.length<9||Ads_yp1!='')?Ads_yp1:arrIntern[8];Ads_xl=0;Ads_yl=0;QQbD(QQfB[Ads_sec]+'/dat/cjf/'+QQqD(Ads_iid)+'.js');}else
{QQtB='';QQvB=0;QQmC();}}function QQqC(QQi)
{var QQj=[];var QQk=QQi.length;var QQl;var QQm='';var QQn='';for(QQl=0;QQl<QQk;QQl+=2)
{QQm=QQi[QQl+1];if(Ads_cnturl!='')
{QQn=QQoD(Ads_cnturl,'[url]',escape(QQm));QQm=QQoD(QQn,'[url_plain]',QQm);}QQj[QQl/2+1]=Ads_CountUrl+escape(QQm)+'&bidx='+QQi[QQl];}return QQj;}function SAS()
{var QQo=false;QQuC();QQo=QQvC();if (QQo==true)
{if((document.cookie.toLowerCase().indexOf('bndlvl')==-1)&&((IAS[13]&4)>0))
QQvE();else
QQrC();}else
{QQsB=false;QQpD(1,'Waiting for asldata.','');}}function QQrC()
{var QQp;if((typeof(Ads_debug)=='undefined')||(Ads_debug!=1))
window.onerror=QQwC;if(((Ads_nid==631)||(Ads_nid==668))&&(NUM_FARM==1))
{ QQfB[0]=['http://e.as-eu.falkag.net'];QQiB[0]=QQfB[0];}if((Ads_nid==80)&&(NUM_FARM==3))
{ QQfB[0]=['http://e.as-us.falkag.net'];QQiB[0]=QQfB[0];}var QQq='undefined';for (intI=0;intI<Ads_T.length;intI++)
{if (typeof(Ads_T_OW)!=QQq)
{if (typeof(Ads_T_OW[intI])!=QQq)
{QQpD(1,'Overwriting Targeting AdsT['+intI+'] ('+Ads_T[intI]+') with',Ads_T_OW[intI]);Ads_T[intI]=Ads_T_OW[intI];}}}if(typeof(Ads_cmd)==QQq) Ads_cmd='';if(typeof(Ads_kid)==QQq) Ads_kid=0;if(typeof(Ads_bid)==QQq) Ads_bid=0;if(typeof(Ads_xl)==QQq) Ads_xl=0;if(typeof(Ads_yl)==QQq) Ads_yl=0;if(typeof(Ads_xp)==QQq) Ads_xp='';if(typeof(Ads_yp)==QQq) Ads_yp='';if(typeof(Ads_xp1)==QQq) Ads_xp1='';if(typeof(Ads_yp1)==QQq) Ads_yp1='';if(typeof(Ads_opt)==QQq) Ads_opt=0;if(typeof(Ads_wrd)==QQq) Ads_wrd='';if(typeof(Ads_prf)==QQq) Ads_prf='';if(typeof(Ads_par)==QQq) Ads_par='';if(typeof(Ads_cnturl)==QQq) Ads_cnturl='';if(typeof(Ads_ref)==QQq) Ads_ref=0;if(typeof(Ads_anc)==QQq) Ads_anc='';if(typeof(Ads_cmb)==QQq) Ads_cmb=[];if(typeof(Ads_uid)==QQq) Ads_uid='';if(typeof(Ads_bgc)==QQq) Ads_bgc='';Ads_cmd=Ads_cmd.toLowerCase();if(Ads_ref==0)
Ads_ref=IAS[12];if(Ads_bgc=='')
{if(typeof(IAS[16])!=QQq)
Ads_bgc=IAS[16];}QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+Ads_kid+'&wrd='+escape(Ads_wrd) +'&bid='+Ads_bid+'&prf='+escape(Ads_prf) +'&xl='+Ads_xl+'&par='+escape(Ads_par) +'&yl='+Ads_yl+'&cnturl='+Ads_cnturl+'&debug='+Ads_debug +'&xp='+Ads_xp+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+Ads_yp+'&ref='+Ads_ref +'&xp1='+Ads_xp1+'&yp1='+Ads_yp1+'&opt=';var QQr='" width="'+Ads_xl+'" height="'+Ads_yl+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>';if(Ads_ref>0)
{document.write('<iframe src="'+QQp+Ads_opt+QQr);Ads_ref=0;return;}QQfF();if((Ads_bgc!='')&&(Ads_bgc!='-1')&&(document.body!=null))
document.body.style['backgroundColor']='#'+Ads_bgc;if(((IAS[13]&8)>0)&&(QQwE[10]==0))
QQsE();QQqA='';QQrA='';QQtA=0;QQuA=0;QQvA='';QQsA=-1;if(NUM_FARM==3)
KAS[KAS.length]=[-1,100,-1,100,[],0,0,0,0,100];if((Ads_kid==0)||(Ads_kid==''))
QQsA=QQaE();else
{QQk=KAS.length;QQsA=0;while((QQsA<QQk)&&(KAS[QQsA][0]!=Ads_kid))
QQsA++;if(QQsA==QQk)
QQsA=-1;}if((Ads_opt&256)!=0)
{if(QQsA!=-1)
Ads_skid=KAS[QQsA][0];else
Ads_skid=0;}else
{if(QQsA!=-1)
{QQtA=KAS[QQsA][0];QQuA=KAS[QQsA][6];if(QQuA!=0)
QQvA='&sid='+QQuA;if(QQtA>0)
{QQbD(QQfB[Ads_sec]+'/dat/bjf/'+QQqD(QQtA)+'.js');}else
DAS();}else
{DAS();}}}function DAS()
{var QQs,QQk,QQt,QQu,QQv,QQw,QQx,QQy,QQz;QQy=['',''];QQz=[];var QQA='';var QQB=['_blank','_self','_parent','_top'];Ads_Timestamp=QQmD();var QQd=0;var QQC,QQf,QQg;if(IAS[9]==1)
{QQC='adsolut.gif';QQf=234;QQg=60;}else
{QQC='trpix.gif';QQf=1;QQg=1;}QQbB=QQmA[NUM_FARM];if(IAS[9]==4)
QQbB='Werbung';if (NUM_FARM==2){QQbB='onmouseover="self.status=\'\';return true;" ';}else{QQbB='onmouseover="self.status=\''+QQbB+'\';return true;" ';}if(IAS[9]==5)
QQbB='';var QQD=1;var QQa='http://www.falkag.de';// Ziel-Url
var QQE=(NUM_FARM==2)?'':'Falk AdSolution';var QQF=0;var QQG='';var QQH='';var QQI='';var QQJ='';var QQK='';var QQL=0;var QQM=0;var QQN=0;var QQO=0;var QQP=1;var QQQ=2;var QQe='';var QQR='';var QQi=[];var QQS=0;var QQT='';var QQU='';var QQV=false;var QQW=0;var QQX=false;var QQY,QQZ,QQAa,QQBa,QQCa,QQDa,QQEa,QQFa,QQGa,QQHa;if(QQtA!=0)
{if((Ads_bid==0)||(Ads_bid==''))
QQs=QQbE(QQsA,QQtA);else
{QQk=BAS.length;QQs=0;while((BAS[QQs][0]!=Ads_bid)&&(QQs<QQk))
QQs++;if(QQs==QQk)
QQs=-1;}if(QQs!=-1)
QQd=BAS[QQs][0];}if(QQd>0)
{QQD=BAS[QQs][3];QQC=BAS[QQs][4];QQa=BAS[QQs][5];QQE=BAS[QQs][6];QQF=BAS[QQs][12];QQG=BAS[QQs][7];QQH=BAS[QQs][8];QQI=BAS[QQs][9];QQJ=BAS[QQs][10];QQK=BAS[QQs][11];QQf=BAS[QQs][13];QQg=BAS[QQs][14];QQL=BAS[QQs][15];QQM=BAS[QQs][16];QQP=BAS[QQs][17];QQQ=BAS[QQs][18];QQe=BAS[QQs][19];QQR=BAS[QQs][20];QQi=BAS[QQs][22];QQS=BAS[QQs][23];QQT=BAS[QQs][24];QQU=BAS[QQs][25];QQW=BAS[QQs][27];if (!QQeB)
QQeB=(BAS[QQs][26]==1);Ads_klist+=QQtA+'#';QQv=KAS[QQsA][4][25];if(QQv>0)
{if(typeof(Ads_fcount[QQv])=='undefined')
Ads_fcount[QQv]=1;else
Ads_fcount[QQv] ++;}}if(QQtA>0)
QQy=QQiF(QQtA,QQsA,QQd,QQs,((QQF&4096)>0));if(QQtA==-1)
{QQtA=99999999;QQd=99999999;}QQz=QQhD(QQtA,QQd,QQy);QQpD(1,'Count-String [Click/Impression]',QQz[0]+'/'+QQz[1]);Ads_skid=QQtA;Ads_sbid=QQd;QQH=(QQH=='')?QQa:QQH;QQY=(QQF&24);QQZ=QQB[QQF&3];QQCa=((QQF&64)>0)&&((Ads_opt&64)==0);QQAa=(QQF&128)>0;QQBa=(QQF&512)>0;QQV=(QQT=='_search')||(QQT=='_media');QQDa=((QQF&1024)>0)&&Ads_ModulEffects;QQEa=((QQF&8192)>0);QQXj=((Ads_opt&2)>0);QQFa=(QQF&2048)>0;QQGa=(QQR.length>0);QQX=(QQW==0)?false:true;QQf=(Ads_xl>0)?Ads_xl:QQf;QQg=(Ads_yl>0)?Ads_yl:QQg;QQL=(Ads_xp!='')?Ads_xp:QQL;QQM=(Ads_yp!='')?Ads_yp:QQM;QQN=(Ads_xp1!='')?Ads_xp1:QQN;QQO=(Ads_yp1!='')?Ads_yp1:QQO;QQyA=(QQF&4096)>0;Ads_opt|=(QQF&16384)>0?64:0;Ads_opt|=IAS[3]*32;if (QQX&&Ads_cmd!='win')
{var QQIa='nid='+Ads_nid+'&iid='+Ads_iid+'&bid='+QQd+'&rdm='+QQmD();document.write(QQkD(1,QQIa));}if(Ads_anc!='')
{QQw=true;QQA=Ads_anc;Ads_anc='';}QQa=QQnC(QQa);QQH=QQnC(QQH);if(Ads_cnturl!='')
{QQHa=QQoD(Ads_cnturl,'[url]',escape(QQa));QQa=QQoD(QQHa,'[url_plain]',QQa);QQHa=QQoD(Ads_cnturl,'[url]',escape(QQH));QQH=QQoD(QQHa,'[url_plain]',QQH);}if(QQwB.length!=0)
{QQqA+=QQwB[13];QQrA+=QQwB[14];}if((QQD==3)||(QQD==4)||(QQD==8))
{Ads_LinkUrl=QQa;Ads_CountUrl=QQoC('',QQz[0]);Ads_CountUrl_ne=Ads_CountUrl.substr(0,Ads_CountUrl.length-1)+'ne=';Ads_ClickUrl=Ads_CountUrl+escape(QQa);Ads_MultiUrl=QQqC(QQi);Ads_ViewCode=QQkD(0,QQz[1]);Ads_ViewUrl=QQiD()+QQz[1];}if(QQD==1)
QQI=QQiB[Ads_sec]+'/dat/bgf/'+QQC;if(QQwB.length!=0)
{if(!QQAa)
{QQAa=QQwB[0];QQCa=QQwB[1];QQBa=QQwB[2];QQQ=QQwB[3];QQDa=QQwB[4];QQEa=QQwB[5];}if(!QQGa)
{QQGa=QQwB[6];QQR=QQwB[7];}QQL=QQwB[8];QQM=QQwB[9];QQN=QQwB[16];QQO=QQwB[17];QQY=QQwB[10];IAS[2]=QQwB[11];IAS[11]=QQwB[12];QQA=QQwB[15];QQw=(QQA!='');QQwB=[];}if(QQD==5)
{QQwB=[QQAa,QQCa,QQBa,QQQ,QQDa,QQEa,QQGa,QQR,QQL,QQM,QQY,IAS[2],IAS[11],QQqA,QQrA,QQA,QQN,QQO];QQAa=false;QQGa=false;QQw=false;IAS[2]=0;}if((Ads_cmd=='lnk')&&(QQD!=5))
{self.location.href=QQoC(QQa,QQz[0]);QQAa=false;QQGa=false;QQw=false;QQD=6;return;}if(QQAa&&!QQV)
{if (!QQXj)
QQt=QQmI(QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,'');else
QQt=window;if(QQCa)
{if(window.innerHeight)
{QQf=QQt.innerWidth;QQg=QQt.innerHeight;}else
{QQf=QQt.document.body.clientWidth;QQg=QQt.document.body.clientHeight;}}if (!QQXj||(QQXj&&Ads_cmd=='win'))
if(QQBa&&(QQQ==0))
QQt.blur();else if(QQBa)
QQt.setTimeout('window.blur();',QQQ*1000);}else
QQt=window;if(QQw)
document.write(QQtD('Ads_place'+Ads_iid));else if(Ads_ModulEffects&&QQGa)
{if(QQY==16)
QQY=1;else if(QQY==24)
QQY=2;else
QQY=0;QQtH(Ads_iid,QQf,QQg,QQL,QQM,QQY,QQR,QQAa,QQt);QQuH(Ads_iid,Ads_sec);}QQpD(1,'Banner-Typ/PopUp',QQD+'/'+QQAa);QQoI(QQtA,QQd,QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,'',QQXj);if (!QQXj||(QQXj&&(Ads_cmd =='win')))
{if(QQD<2)
QQgI(QQt,QQAa,QQz,QQI,QQa,QQZ,QQf,QQg,QQE,QQV,QQT,QQd,QQL,QQM);else if(QQD==2)
QQhI(QQt,QQAa,QQz,QQC,QQa,QQZ,QQf,QQg,QQE,QQG,QQH,QQFa,QQP,QQU);else if(QQD==3)
QQiI(QQt,QQAa,QQz,QQtA,QQd,QQy,QQGa,QQf,QQg,QQS,QQT,QQw,'/dat/brf/',0,QQV,QQXj);else if(QQD==4)
QQjI(QQt,QQAa,QQz,QQJ,QQK,QQGa,QQf,QQg,QQw);else if(QQD==5)
QQpC(QQtA,QQd,QQe,QQf,QQg);else if(QQD==8)
QQiI(QQt,QQAa,QQz,QQtA,QQd,QQy,QQGa,QQf,QQg,QQS,QQT,QQw,'/dat/bfx/',parseInt(QQe,10),QQV,QQXj);}QQpD(3,'Banner-display finished');QQtE();if(QQw)
{document.write(QQuD());setInterval('QQwD("Ads_place'+Ads_iid+'","'+QQA+'",'+QQf+','+QQg+');',20);}if(Ads_ModulEffects&&QQGa)
QQvH(Ads_iid);if(QQD!=5)
QQmC();Ads_idl+='#'+Ads_iid+'#';if((IAS[2]>0)&&(Ads_idl.indexOf('#'+IAS[2]+'#')==-1)&&(IAS[11]>(Math.random()*100)))
{Ads_kid=0;Ads_bid=0;Ads_xl=0;Ads_yl=0;QQbD(QQfB[Ads_sec]+'/dat/cjf/'+QQqD(IAS[2])+'.js');}QQk=Ads_cmb.length;for(QQl=0;QQl<QQk;QQl++)
{if(Ads_cmb[QQl]!='')
{QQx=Ads_cmb[QQl];Ads_cmb[QQl]='';QQl=QQk;Ads_pth='';Ads_iid='';eval(QQx);if(Ads_pth!='')
QQbD(QQfB[Ads_sec]+'/dat/njf/'+Ads_pth+'.js');else
QQbD(QQfB[Ads_sec]+'/dat/cjf/'+QQqD(Ads_iid)+'.js');}}}function CAS()
{QQsC(0);}function CASF()
{var QQJa=new Date();Ads_T=[0,0,'',0,0,'','','','',QQJa,0,0,0,0];QQsC(1);}function QQsC(QQKa)
{if(typeof(Ads_debug)=='undefined') Ads_debug=0;var QQLa=new Date(Ads_T[9]);var QQMa=new Date();Ads_T[9]=QQLa-QQMa;var QQNa=Ads_T[0]+'#'+Ads_T[1]+'#'+Ads_T[2]+'#'+Ads_T[3]+'#'+Ads_T[4]+'#'+Ads_T[5]+'#'+Ads_T[6]+'#'+escape(Ads_T[7])+'#'+escape(Ads_T[8])+'#'+Ads_T[9]+'#'+Ads_T[10]+'#'+Ads_T[11]+'#'+Ads_T[12]+'#'+Ads_T[13];document.cookie='ASLTRG'+NUM_FARM+'='+QQNa+QQfD(60*((QQKa==0)? 24:1));Ads_Data[NUM_FARM]=Ads_T;QQpD(1,'Load targeting-infos from server ('+((QQKa==0)? 'Origin':'Failover')+')',QQNa);if (QQsB==false)
{QQsB=true;SAS();}}function LAS(QQOa)
{Ads_iid=0;var QQb='pth='+QQOa+'&xl='+Ads_xl+'&yl='+Ads_yl;if(typeof(Ads_channels)!='undefined')
QQb+='&chn='+escape(Ads_channels);QQyA=false;document.write(QQkD(0,QQb));}function QQtC()
{QQwA=new Date();QQaB=-1;QQdB=0;document.cookie='BSUID=1'+QQfD(60*24*30);QQzA=false;if(typeof(Ads_debug)=='undefined') Ads_debug=0;if(typeof(Ads_klist)!='string') Ads_klist='';if(typeof(Ads_fcount)!='object') Ads_fcount=[];if(typeof(Ads_idl)!='string') Ads_idl='';if(typeof(garrIFrames)=='undefined') garrIFrames=[];QQpD(3,'Global Init');QQpD(1,'VAS Build Version:',Ads_Build);}function QQuC()
{if(typeof(Ads_sec)=='undefined') Ads_sec=IAS[1];QQpD(1,'Protocoll used',(Ads_sec==0)?'HTTP':'HTTPS');if(typeof(NUM_FARM)=='undefined')
NUM_FARM=1;if(typeof(Ads_farmid)!='undefined')
NUM_FARM=Ads_farmid;QQpD(1,'Setting configuration for farm',NUM_FARM);QQfB=[QQbA[NUM_FARM],QQcA[NUM_FARM]];QQgB=[QQhA[NUM_FARM],QQiA[NUM_FARM]];QQhB=[QQjA[NUM_FARM],QQkA[NUM_FARM]];QQiB=[QQdA[NUM_FARM],QQeA[NUM_FARM]];QQjB=[QQfA[NUM_FARM],QQgA[NUM_FARM]];}function QQvC()
{var QQNa=document.cookie+';';var QQPa=(QQNa.indexOf('BSUID=')!=-1);var QQQa=QQNa.indexOf('ASLTRG'+NUM_FARM+'=');var QQRa,QQZ;if (typeof(Ads_Data[NUM_FARM])!='undefined')
{QQpD(1,'Load targeting-infos targeting array ['+NUM_FARM+']',Ads_Data[NUM_FARM]);Ads_T=Ads_Data[NUM_FARM];return true;}if(QQQa!=-1)
{QQRa=QQNa.indexOf(';',QQQa);QQZ=QQNa.substring(QQQa+8,QQRa);Ads_T=QQZ.split('#');Ads_T[7]=unescape(Ads_T[7]);Ads_T[8]=unescape(Ads_T[8]);Ads_Data[NUM_FARM]=Ads_T;QQpD(1,'Load targeting-infos from cookie',QQZ);return true;}else
{QQpD(1,'#-#ASLDATA-load start','');QQbD(QQhB[Ads_sec]+ (QQPa?('?rdm='+QQmD()):''));QQpD(1,'#-#ASLDATA-load ende','');return false;}}function QQwC(QQSa,QQTa,QQUa)
{return true;}function QQxC()
{var QQVa=(QQyA?1:0);QQVa+=((QQeB)?2:0);QQpD(1,'FLG',QQVa);return QQVa;}function QQyC(QQWa,QQXa)
{if ((QQWa==QQxB)&&(QQXa==QQyB))
return true;else
return false;}function QQzC(QQYa,QQZa)
{var QQAb;var QQBb;QQBb=false;if(!isNaN(QQYa))
{QQAb=parseInt(QQYa);QQBb=QQAb>=0&&(QQZa||QQAb>0);}return QQBb;}function QQaD(QQCb)
{var QQDb,QQEb;var QQFb,QQGb,QQHb,QQIb,QQJb,QQKb;var QQY,QQLb,QQMb,QQNb,QQOb;var QQPb;var QQQb;QQDb=QQCb.split('-');QQQb=false;QQEb=[];QQPb=true;if(QQDb[0]!=null&&QQDb[1]!=null)
{QQFb=QQDb[0];QQGb=QQDb[1];QQPb=QQPb&&QQzC(QQGb,false);if(QQPb&&QQDb[2]!=null)
{QQHb=QQDb[2];QQPb=QQzC(QQHb,false);if(QQPb&&QQDb[3]!=null)
{QQIb=QQDb[3];QQPb=QQzC(QQIb,true);if(QQPb&&QQDb[4]!=null)
{QQJb=QQDb[4];if(QQPb&&QQDb.length>5)
{QQY=5;while(QQPb&&QQY<QQDb.length)
{if(QQDb[QQY]==''&&QQDb[QQY+1]!=null)
{QQKb=QQDb[QQY+1];QQPb=QQzC(QQKb,true);QQEb[QQEb.length]='-'+QQKb;QQY=QQY+2;}else
{QQKb=QQDb[QQY];QQPb=QQzC(QQKb,true);QQEb[QQEb.length]=QQKb;QQY=QQY+1;}}QQPb=QQPb&&(QQEb.length==0||QQEb.length==2||QQEb.length==4);}}}}if(QQPb)
{QQQb=[QQFb,QQGb,QQHb,QQIb,QQJb];for (var intI=0;intI<QQEb.length;intI++)
{QQQb[QQQb.length]=QQEb[intI];}}}return QQQb;}QQtC();// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000059)
function QQfI(QQFh,QQRj)
{return (QQFh==0)?'':' '+QQRj+'="'+QQFh+'"';}function QQgI(QQt,QQAa,QQz,QQI,QQa,QQZ,QQf,QQg,QQE,QQV,QQT,QQd,QQL,QQM)
{QQI=QQnC(QQI);if(QQAa&&QQV&&!QQXj)
{QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+QQtA+'&wrd='+escape(Ads_wrd) +'&bid='+QQd+'&prf='+escape(Ads_prf) +'&xl='+QQf+'&par='+escape(Ads_par) +'&yl='+QQg+'&cnturl='+Ads_cnturl+'&debug=0' +'&xp='+QQL+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+QQM+'&ref='+Ads_ref+'&opt=' +2 +'&cmd=win';QQpD(1,'Sidebar',QQp);QQtSide=window.open(QQp,QQT);}else
{if(QQAa)
QQkI(QQt,QQE);QQt.document.write('<a href="'+QQoC(QQa,QQz[0]) +'" target="'+QQZ+'" '+QQbB+'onmouseout="self.status=\'\';return true;">');QQt.document.write('<img src="'+QQI+'"'+QQfI(QQf,'width')+QQfI(QQg,'height')+' border="0" id="Ads_img'+Ads_iid+'" name="Ads_img'+Ads_iid+'" alt="'+QQE+'"></a>');QQlD(QQt,QQz[1]);if(QQAa)
QQlI(QQt);}if (QQyC(Ads_iid,QQtA))
{QQtB='';QQvB=0;}}function QQhI(QQt,QQAa,QQz,QQC,QQa,QQZ,QQf,QQg,QQE,QQG,QQH,QQFa,QQP,QQU)
{var QQUj=QQoD(QQz[0],'&rdm='+Ads_Timestamp,'');if(QQAa)
QQkI(QQt,QQE);QQa=QQoC(QQa,QQUj);QQH=QQoC(QQH,QQUj);QQC=QQiB[Ads_sec]+'/dat/bgf/'+QQC;QQG=QQiB[Ads_sec]+'/dat/bgf/'+QQG;QQjC=QQa;QQkC=QQoC('',QQUj);var QQVj=QQC;if(typeof(QQU)=='undefined') QQU='';if(QQU=='')
QQVj+='?clickTag='+escape(QQa)+'&url='+escape(QQa);else if(QQU!='0')
QQVj+='?'+QQU+'='+escape(QQa);var QQQc;if(QQP<=QQsD(1))
{QQt.document.write('<OBJECT classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http'+((Ads_sec==1)?'s':'')+'://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=3,0,0,0" id=banner'+QQfI(QQf,'width')+QQfI(QQg,'height')+'">');QQt.document.write('<PARAM NAME=movie VALUE="'+QQVj+'"><PARAM NAME=play VALUE=true><PARAM NAME=autoplay VALUE=true><PARAM NAME=wmode VALUE=opaque><PARAM NAME=quality VALUE=autohigh><PARAM name=scale value=exactfit>');QQt.document.write('<EMBED src="'+QQVj+'" quality=autohigh autoplay=true play=true wmode=opaque scale=exactfit swLiveConnect=TRUE'+QQfI(QQf,'width')+QQfI(QQg,'height')+' TYPE="application/x-shockwave-flash" PLUGINSPAGE="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"></EMBED></OBJECT>');}else
{QQt.document.write('<a href="'+QQH+'" target="'+QQZ+'" '+QQbB+' onmouseout="self.status=\'\';return true;"><img src="'+QQG+'"'+QQfI(QQf,'width')+QQfI(QQg,'height')+' border="0" alt="'+QQE+'"></a>');}QQlD(QQt,QQz[1]);if(QQAa)
QQlI(QQt);if (QQyC(Ads_iid,QQtA))
{QQtB='';QQvB=0;}}function QQiI(QQt,QQAa,QQz,QQc,QQd,QQy,QQGa,QQf,QQg,QQS,QQT,QQw,QQOa,QQWj,QQV,QQXj)
{var QQC=QQfB[Ads_sec]+QQOa+QQqD((QQWj>0)?QQWj:((QQS==0)?QQd:QQS));var QQYj,QQCg;var QQZj=[];QQZj=QQgD(QQc,QQd,QQy);iid=Ads_iid;bid=QQd;rdm=QQZj[2];if(QQAa||((QQGa||QQw)&&(QQqB||QQrB)))
{var QQAk='*';for(QQCg=1;QQCg<Ads_MultiUrl.length;QQCg++)
{QQa=Ads_MultiUrl[QQCg];QQAk+=QQa.substring(Ads_CountUrl.length,QQa.length)+'*';}QQYj=Ads_wid+'#'+Ads_iid+'#'+QQc+'#'+QQd+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+(QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQxC()+'&')+'#'+Ads_LinkUrl+'#'+QQAk+'#'+QQiD();}if(QQAa&&QQV&&!QQXj)
{window.open(QQC+'.html?'+escape(QQYj),QQT);}else if(QQAa)
{QQt.location.href=QQC+'.html?'+escape(QQYj);}else if((QQGa||QQw)&&(QQqB||QQrB))
{document.write('<iframe src="'+QQC+'.html?'+escape(QQYj)+'" width="'+QQf+'" height="'+QQg+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{rdm=QQZj[0];if(QQWj>0)
{Ads_xl=QQf;Ads_yl=QQg;QQlD(QQt,QQz[1]);if ((Ads_opt&4096)>0)
{QQpD(1,'Serve AFX Out Of Frame','');var QQAk='*';for(QQCg=1;QQCg<Ads_MultiUrl.length;QQCg++)
{QQa=Ads_MultiUrl[QQCg];QQpD(1,'Ads_MultiUrl['+QQCg+']',QQa.substring(Ads_CountUrl.length,QQa.length));QQaShort=QQa.substring(Ads_CountUrl.length,QQa.length);QQpD(1,'Index of',QQaShort.indexOf(".falkag.net/dat/bgf/trpix.gif&bidx="));if (QQaShort.indexOf(".falkag.net/dat/bgf/trpix.gif&bidx=")>=0)
{QQAk+='PX'+QQaShort.substring(QQaShort.indexOf('&')+5,QQaShort.length)+'*';}else
{QQAk+=QQaShort+'*';}}QQpD(1,'QQAk',QQAk);QQYj=Ads_wid+'#'+Ads_iid+'#'+QQc+'#'+QQd+'#'+Ads_xwid+'#'+Ads_xiid+'#'+Ads_wrd+'#'+Ads_prf+'#'+Ads_par+'#'+Ads_Timestamp+'#'+rdm+'#'+(QQgB[Ads_sec]+QQpA[NUM_FARM]+'flg='+QQxC()+'&')+'#'+Ads_LinkUrl+'#'+QQAk+'#'+QQiD()+'#'+NUM_FARM+'#'+QQfB[Ads_sec]+'#'+QQWj;var QQBk=document.referrer;var QQCk='';var QQDk='';var QQEk=QQBk.indexOf('://');if (QQEk>-1)
{QQCk=QQBk.substring(0,(QQEk+3));QQDk=QQBk.substring((QQEk+3),QQBk.length);var QQEk=QQDk.indexOf('/');if (QQEk>-1)
QQDk=QQDk.substring(0,QQEk);}QQpD(1,'Loading ',QQCk+QQDk+'/afx_frame.html?'+ escape(QQYj));document.write('<iframe src="'+QQCk+QQDk+'/afx_frame.html?'+escape(QQYj)+'" width="1" height="1" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');}else
{if ((typeof(Ads_FXPL)=='undefined')||(Ads_FXPL==false))
{QQbD(QQfB[Ads_sec]+'/dat/dlv/afxplay.js');Ads_FXPL=true;}QQbD(QQC+'.js');}}else
QQbD(QQC+'.js');}if (QQyC(Ads_iid,QQtA))
{QQtB='';QQvB=0;}}function QQjI(QQt,QQAa,QQz,QQJ,QQK,QQGa,QQf,QQg,QQw)
{QQK=QQnC(unescape(QQK));QQJ=QQnC(unescape(QQJ));if(QQAa)
QQt.location.href=QQJ;else
{if(((QQGa||QQw)&&QQqB)||(QQK==''))
document.write('<iframe src="'+QQJ+'" width="'+QQf+'" height="'+QQg+'" noresize scrolling="no" hspace="0" vspace="0" frameborder="0" marginheight="0" marginwidth="0"></iframe>');else
QQbD(QQK);}QQlD(window,QQz[1]);if (QQyC(Ads_iid,QQtA))
{QQtB='';QQvB=0;}}function QQkI(QQt,QQE)
{QQt.document.open();QQt.document.write('<html><head><title>'+QQE+'</title></head><body topmargin="0" leftmargin="0" rightmargin="0" marginwidth="0" marginheight="0"><table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0" align="center"><tr><td valign="middle"><center>');}function QQlI(QQt)
{QQt.document.write('</center></td></tr></table></body></html>');QQt.document.close();}function QQmI(QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,QQT)
{var QQu='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var QQFk='Ads_Popup'+Ads_iid;var QQGk,QQHk;var QQIk=0;var QQJk=0;if (!QQV&&QQT!='')
QQFk=QQT;QQu=QQnI(QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,QQT,QQXj);if((Ads_opt&32)>0)
QQFk+=''+Math.round(Math.random()*100000);QQt=open('',QQFk,QQu);if(QQCa&&(!QQnB))
QQt.moveTo(0,0);if(QQDa)
QQcI(QQt,QQf,QQg);return QQt;}function QQnI(QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,QQT,QQXj)
{var QQu='locationbar=no,directories=no,statusbar=no,toolbar=no,location=no,menubar=no,personalbar=no';var QQFk='Ads_Popup'+Ads_iid;var QQGk,QQHk;var QQIk=0;var QQJk=0;if (!QQV&&QQT!='')
QQFk=QQT;if(QQCa)
{if (QQoB)
{QQIk=10;QQJk=30;}else if (QQpB)
{QQIk=20;QQJk=35;}QQu+=',scrollbars=no,resizable=no,width='+(screen.availWidth-QQIk)+',height='+(screen.availHeight-QQJk)+',screenX=0,screenY=0';if(QQnB)
QQu='fullscreen=yes';}else
{if(QQDa)
QQu+=',resizable=yes,width=90,height=70,innerWidth=90,innerHeight=70';else
QQu+=',resizable=no,width='+QQf+',height='+QQg;if(QQEa)
QQu+=',scrollbars=yes';else
QQu+=',scrollbars=no';if((Ads_opt&64)>0)
QQu='locationbar=yes,scrollbars=yes,directories=yes,statusbar=yes,toolbar=yes,location=yes,menubar=yes,personalbar=yes,resizable=yes,width='+QQf+',height='+QQg;if(QQY==16)
{QQL=(screen.width-QQf-25)*QQL/100;QQM=(screen.height-QQg-50)*QQM/100;}else if(QQY==24)
{QQL=(screen.width-QQf-25)*Math.random();QQM=(screen.height-QQg-50)*Math.random();}if (!QQqB)
QQu+=",screenX="+QQL+",screenY="+QQM;else
QQu+=",left="+QQL+",top="+QQM;}return QQu;}function QQoI(QQtA,QQd,QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,QQT,QQXj)
{var QQKk='';QQKk='<scr'+'ipt language="JavaScript">'+'function Ads_PopUp() {';if (Ads_cmd!='win'&&QQXj&&(QQd>0))
{QQpD(1,'POP ON EXIT','');var QQFk='Ads_Popup'+Ads_iid;if (!QQV&&QQT!='')
QQFk=QQT;if((Ads_opt&32)>0)
QQFk+=''+Math.round(Math.random()*100000);QQu=QQnI(QQf,QQg,QQL,QQM,QQY,QQCa,QQBa,QQQ,QQDa,QQEa,QQV,'',true);QQp=QQfB[Ads_sec]+'/dat/dlv/aslframe.html?dat='+Ads_iid +'&kid='+QQtA+'&wrd='+escape(Ads_wrd) +'&bid='+QQd+'&prf='+escape(Ads_prf) +'&xl='+QQf+'&par='+escape(Ads_par) +'&yl='+QQg+'&cnturl='+Ads_cnturl+'&debug=0' +'&xp='+QQL+'&sec='+Ads_sec+'&bgc='+Ads_bgc +'&yp='+QQM+'&ref='+Ads_ref+'&opt=' +2 +'&cmd=win';QQkB[QQkB.length]='QQt=open(\''+QQp+'\',\''+QQFk+'\',\''+QQu+'\');';}for (var intI=0 ;intI<QQkB.length ;intI++)
{QQKk+=QQkB[intI];}QQKk+='}'+'</scr'+'ipt>';document.writeln(QQKk);}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000059)
var QQwE=[];var QQxE=[];var QQyE;function QQzE(QQSg,QQTg,QQUg,QQRe)
{if(typeof(QQSg)=='undefined')
return [];var QQl,QQk;var QQVg=[];var QQWg=QQSg.split('x');var QQXg=QQWg[0];var QQYg=QQTg-QQXg;var QQk=QQWg.length;QQxE[QQRe]=[];for(QQl=1;QQl<QQk;QQl++)
{QQDi=QQWg[QQl].split(':');if(QQUg&&(QQDi[2]==-1))
QQVg[QQDi[0]]=[QQDi[1],-1];QQDi[2]-=QQYg;if(QQDi[2]>0)
QQVg[QQDi[0]]=[QQDi[1],QQDi[2]];if (typeof(QQxE[QQRe])=='undefined')
QQxE[QQRe]=[];QQxE[QQRe][QQxE[QQRe].length]=QQDi[0];}return QQVg;}function QQaF(QQVg,QQTg,QQRe)
{var QQSc;var QQSg=QQTg;var QQl;if (typeof(QQxE[QQRe])!='undefined')
{for (var intI=0;intI<QQxE[QQRe].length;intI++)
{QQl=QQxE[QQRe][intI];if (typeof(QQVg[QQl])!='undefined')
{QQSg+='x'+QQl+':'+QQVg[QQl][0]+':'+QQVg[QQl][1];}}}return QQSg;}function QQbF(QQZg,QQAh)
{while(QQZg.length>800)
QQZg=QQZg.substr(0,QQZg.lastIndexOf('#',QQZg.length-2)+1);QQwE[QQAh]=QQZg;}function QQcF(QQAh,QQAb)
{var QQBh='111';var QQCh='@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`';var QQk=0;var QQYa='#'+QQAb+':';var QQZg=QQwE[QQAh];var QQDh='';var QQY=QQZg.indexOf(QQYa);var QQEh=new Date();var QQFh,QQGh,QQHh,QQIh,QQHe;var QQJh,QQKh,QQLh,QQMh;if(QQZg=='')
QQZg='#';if(QQY>-1)
{QQGh=QQZg.substr(QQY+QQYa.length,3+QQAh);if(QQY>0)
QQDh=QQZg.substr(0,QQY);QQFh=QQZg.length-QQY-QQYa.length-3-QQAh;if(QQFh>0)
QQDh+=QQZg.substr(QQY+QQYa.length+3+QQAh,QQFh);QQZg=QQDh;QQHh=new Date(QQCh.indexOf(QQGh.charAt(0))+2000,QQCh.indexOf(QQGh.charAt(1))-1,QQCh.indexOf(QQGh.charAt(2)));QQEh.setHours(0);QQEh.setMinutes(0);QQEh.setSeconds(0);QQIh=(QQEh.getTime()-QQHh.getTime())/1000/60/60/24;intAltWTag=(QQHh.getDay()==0?7:QQHh.getDay());intNeuWTag=(QQEh.getDay()==0?7:QQEh.getDay());intAltMTag=QQHh.getDate();intNeuMTag=QQEh.getDate();QQBh=((QQIh>0.1)?'1':'0')+(((QQIh>6)||(intAltWTag>intNeuWTag))?'1':'0')+((((QQIh>29)||(intAltMTag>intNeuMTag))&&(QQAh!=1&&QQAh!=14))?'1':'0');if(QQAh==1||QQAh==14)
QQk=QQCh.indexOf(QQGh.charAt(3));}QQGh='#'+QQAb+':';QQHe=QQEh.getYear();if(QQHe<1900)
QQHe+=1900;QQGh+=QQCh.charAt(QQHe-2000);QQGh+=QQCh.charAt(QQEh.getMonth()+1);QQGh+=QQCh.charAt(QQEh.getDate());if(QQAh==1||QQAh==14)
{QQk++;if(QQk>21)
QQk=21;QQGh+=QQCh.charAt(QQk);QQBh+=QQCh.charAt(QQk);}QQZg=QQGh+QQZg;QQbF(QQZg,QQAh);return QQBh;}function QQdF(QQYa,QQAh,QQNh)
{var QQQa,QQRa,QQFh,QQOh,QQPh;var QQZg=QQwE[QQAh];var QQDh='';var QQQh='';var QQRh=-1;if(QQZg=='')
QQZg='#';QQYa='#'+QQYa+'-';QQQa=QQZg.indexOf(QQYa);if(QQQa!=-1)
QQRa=QQZg.indexOf('#',QQQa+1);if((QQQa!=-1)&&(QQRa!=1))
{QQOh=QQZg.substring(QQQa+QQYa.length,QQRa);if(QQQa>0)
QQDh=QQZg.substr(0,QQQa);QQFh=QQZg.length-QQRa;if(QQFh>0)
QQDh+=QQZg.substr(QQRa,QQFh);QQZg=QQDh;if(QQAh==6)
{QQPh=QQOh.split('-');QQQh=QQPh[0];QQOh=QQPh[1];}QQRh=QQNh-parseInt(QQOh,10);if(QQRh>1200)
QQRh=-1;}QQwE[QQAh]=QQZg;return [QQRh,QQQh];}function QQeF(QQc)
{var QQSh=new Date();var QQRh=QQSh.getHours()*60*60+QQSh.getMinutes()*60+QQSh.getSeconds();var QQTh,QQUh;QQTh=QQdF(Ads_wid,6,QQRh);QQUh=QQdF(QQc,5,QQRh);var QQVh=(QQTh[0]==-1);var QQWh=(QQUh[0]==-1);var QQXh=(QQVh?'1':'0')+(QQWh?'1':'0');if(!QQVh)
QQXh+=QQnD(QQTh[0],4)+QQTh[1];QQbF('#'+Ads_wid+'-'+Ads_iid+'-'+QQRh+QQwE[6],6);QQbF('#'+QQc+'-'+QQRh+QQwE[5],5);return QQXh;}function QQfF()
{var QQUb=QQdD();var QQl,QQYh,QQSc,QQZh,QQAi,QQBi,QQCi,QQDi,QQAh;var QQEi,QQFi;var QQNa=document.cookie;var QQUg=(QQNa.toLowerCase().indexOf('sestest')>-1);document.cookie='SESTEST=1'+QQfD(-1);var QQGi=QQNa.split(';');var QQk=QQGi.length;var QQNc=new Date();QQyE=Math.round(QQNc.getTime()/1000/60);QQwE=['','',[],'','','','',[],[],[],QQdB,'',[],'',''];QQwE=QQgF('',QQGi,QQk,QQUg);if(Ads_uid!='')
{QQGi=Ads_userdata.split(';');QQk=QQGi.length;QQwE[2]=[];for(QQl=1;QQl<(QQk-1);QQl++)
{QQBi=QQGi[QQl].split(',');QQwE[2][QQBi[0]]=[QQBi[1],1];}}if(QQwE[3]=='1')
QQzA=true;}function QQgF(QQUb,QQGi,QQk,QQUg)
{var QQl;var QQwE;var QQSc;QQwE=['','',[],'','','','',[],[],[],QQdB,'',[],'',''];for(QQl=0;QQl<QQk;QQl++)
{QQAh=-1;QQBi=QQGi[QQl].split('=');QQSc=QQBi[0];QQAi=QQBi[1];if(QQSc.charAt(0)==' ')
QQSc=QQSc.substr(1,QQSc.length-1);if(QQSc.substr(0,QQUb.length)==QQUb)
QQZh=QQSc.substring(QQUb.length,QQSc.length);else
QQZh='';if(QQZh=='KIDYMD')
QQwE[1]=QQAi;else if(QQZh=='WIDYMD')
QQwE[0]=QQAi;else if(QQSc=='BSUID')
QQwE[3]=QQAi;else if(QQSc=='BNDLVL')
QQwE[10]=QQAi;else if(QQZh=='VISKAM')
QQwE[5]=QQAi;else if(QQZh=='VISWEB')
QQwE[6]=QQAi;else if(QQZh=='FRQSTR')
{if (QQAi.indexOf("|")!=-1)
QQBi=QQAi.split('|');else
QQBi=QQAi.split(',');QQwE[2]=QQzE(QQBi[0],QQyE,QQUg,2);QQwE[7]=QQzE(QQBi[1],QQyE,QQUg,7);QQwE[8]=QQzE(QQBi[2],QQyE,QQUg,8);QQwE[9]=QQzE(QQBi[3],QQyE,QQUg,9);QQwE[12]=QQzE(QQBi[4],QQyE,QQUg,12);}if(QQZh=='KIDCYMD')
QQwE[14]=QQAi;else if(QQZh=='WIDCYMD')
QQwE[13]=QQAi;}return QQwE;}function QQhF(QQc,QQNd)
{var QQHi,QQIi,QQCe,QQJi;var QQKi='';var QQUb=QQdD();var QQLi=KAS[QQNd][4][5];if(KAS[QQNd][4][4]>0)
QQKi=QQeD(QQLi);else if((KAS[QQNd][5]&1)>0)
{QQKi=QQeD(20);QQLi=20;}if(QQKi!='')
{QQCe=parseInt(QQjF(QQc,2)+1,10);if(Ads_uid!='')
{QQHi=Ads_userdata.split(';'+QQc+',');if(QQHi.length==2)
{QQIi=Ads_userdata.split(','+QQc+';');Ads_userdata=QQHi[0]+';'+QQIi[1];}Ads_userdata+=QQc+','+QQCe+','+QQLi+','+QQc+';';document.write('<img src="http://uboot.as-eu.falkag.net/usr?cmd=write&id='+Ads_uid+'&data='+Ads_userdata+'&rdm='+Math.random()+'" width="1" height="1">');}else
QQkF(QQc,2,QQCe,QQLi);}}function QQiF(QQc,QQNd,QQd,QQs,QQMi)
{var QQUb=QQdD();var QQy=[];var QQNi,QQNa,QQOi;QQhF(QQc,QQNd);if(QQd>0)
{if(BAS[QQs][2][4]>0)
QQkF(QQd,9,QQjF(QQd,9)+1,BAS[QQs][2][5]);}if(((KAS[QQNd][4][22]&1)>0)&&(IAS[4]>0))
QQkF(Ads_wid,7,QQjF(Ads_wid,7)+1,IAS[5]);if(((KAS[QQNd][4][22]&2)>0)&&(IAS[6]>0))
QQkF(Ads_nid,8,QQjF(Ads_nid,8)+1,IAS[7]);if ((typeof(IAS[17])!='undefined')&&(typeof(QQbC[Ads_wid])!='undefined')&&(typeof(KAS[QQNd][13])!='undefined'))
{if(((KAS[QQNd][4][22]&4)>0)&&(KAS[QQNd][13]>0)&&(QQbC[Ads_wid].length>0)&&(typeof(QQbC[Ads_wid][KAS[QQNd][13]])!='undefined'))
{arrFamily=QQbC[Ads_wid][KAS[QQNd][13]];QQkF(arrFamily[0],12,QQjF(arrFamily[0],12)+1,arrFamily[2]);}}QQNa=QQaF(QQwE[2],QQyE,2)+'|' +QQaF(QQwE[7],QQyE,7)+'|' +QQaF(QQwE[8],QQyE,8)+'|' +QQaF(QQwE[9],QQyE,9)+'|' +QQaF(QQwE[12],QQyE,12);QQNi=QQcF(1,QQc);QQOi=QQNi.substr(0,3)+QQcF(0,Ads_wid)+QQNi.substr(3,1);QQy[1]='&bls3='+QQOi;QQuB=QQOi;QQy[1]+='&bls4='+QQeF(QQc);strClickAuswertung=QQcF(14,QQc);QQy[0]='&ucl='+strClickAuswertung.substr(0,3)+QQcF(13,Ads_wid)+strClickAuswertung.substr(3,1);if(QQzA)
QQy[1]+='&uid=1';QQpD(1,'SETTING TOP-LEVEL DOMAIN',QQNa);document.cookie='FRQSTR='+QQNa+QQfD(60*24*365);document.cookie='WIDYMD='+QQwE[0]+QQfD(60*24*30);document.cookie='KIDYMD='+QQwE[1]+QQfD(60*24*30);document.cookie='VISKAM='+QQwE[5]+QQfD(20);document.cookie='VISWEB='+QQwE[6]+QQfD(20);QQpD(1,'Cookie Auswertung [Click/Impression]',QQy[0]+'/'+QQy[1]);return QQy;}function QQjF(QQAb,QQRe)
{if(typeof(QQwE[QQRe][''+QQAb+''])!='undefined')
return parseInt(QQwE[QQRe][''+QQAb+''],10);else
return 0;}function QQkF(QQAb,QQRe,QQCe,QQLi)
{if(typeof(QQwE[QQRe][''+QQAb+''])!='undefined')
QQwE[QQRe][''+QQAb+''][0]=QQCe;else
{if (typeof(QQxE[QQRe])=='undefined')
QQxE[QQRe]=[];QQxE[QQRe][QQxE[QQRe].length]=QQAb;QQwE[QQRe][''+QQAb+'']=[QQCe,QQLi];}}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000059)
function QQxD(QQZc,QQAd)
{var QQl=0;var QQk=QQZc.length;if(QQk==0)
return -1;while((QQl<QQk-1)&&(QQAd>QQZc[QQl][1]))
{QQAd-=QQZc[QQl][1];QQl++;}return QQZc[QQl][0];}function QQyD(QQBd,QQCd,QQDd)
{var QQl,QQEd,QQFd,QQGd;if(QQBd>QQDd)
{QQEd=QQDd/QQBd;for(QQl=QQCd;QQl<QQlB.length;QQl++)
QQlB[QQl][1]*=QQEd;QQBd=QQDd;}QQDd-=QQBd;return QQDd;}function QQzD()
{var QQBb,QQHd,QQId,QQJd,QQKd;var QQLd=-2;var QQMd=KAS.length;var QQDd=100;var QQNd,QQc,QQGd,QQOd,QQPd,QQQd,QQRd,QQSd,QQTd;var QQBd=0;var QQCd;QQlB=[];for (QQNd=0;QQNd<QQMd;QQNd++)
{QQKd=((KAS[QQNd][5]&2)>0);if(KAS[QQNd][2]!=QQLd)
{if(QQLd!=-2)
QQDd=QQyD(QQBd,QQCd,QQDd);QQLd=KAS[QQNd][2];QQBd=0;QQCd=QQlB.length;}QQOd=KAS[QQNd][8];QQPd=KAS[QQNd][10];QQQd=IAS[10];if((QQQd-QQPd)>0)
QQOd=QQOd*QQQd/(QQQd-QQPd);QQGd=KAS[QQNd][1];if(QQOd<=0)
QQOd=QQGd;QQRd=(QQGd/QQOd-1)*2+1;var QQUd=QQRd;var QQVd=false;if (QQRd>10||QQRd<0.1)
QQVd=true;if(QQRd>10)
QQRd=10;else if (QQRd<0.1)
QQRd=0.1;if (QQVd)
QQpD(1,'Factor (before:after)',QQUd+':'+QQRd);QQSd=KAS[QQNd][3];QQGd=QQGd*QQRd*100/((QQSd==0)?100:QQSd);if(isNaN(QQGd))
QQGd=0;QQJd=KAS[QQNd][4];QQBb=QQrE(QQJd,0,KAS[QQNd][0],((KAS[QQNd][5]&4)>0),QQNd);QQId=false;if(QQJd.length>0)
{QQId=((QQJd[0]==0)&&!((QQJd[2]==0)&&(QQJd[3]==1439)));QQHd=(!QQId||QQpE(QQJd[2],QQJd[3]));if(QQId)
QQGd=QQGd*100/KAS[QQNd][9];if(QQBb&&!QQHd&&!QQKd)
{QQqA+='9'+KAS[QQNd][0]+'-';}QQBb=(QQBb&&QQHd);}if((KAS[QQNd][5]&8)>0)
QQGd=KAS[QQNd][1];if(QQKd&&QQBb)
{QQc=KAS[QQNd][0];QQrA+=QQc+'-';QQhF(QQc,QQNd);}else if(QQBb)
{QQlB[QQlB.length]=[QQNd,QQGd,QQId,QQGd];QQBd+=QQGd;}else
{}}QQDd=QQyD(QQBd,QQCd,QQDd);}function QQaE()
{QQzD();var QQWd,QQNd,QQl,QQGd;var QQMd=QQlB.length;var QQXd=0;for (QQNd=0;QQNd<QQMd;QQNd++)
{QQl=QQlB[QQNd][0];QQGd=QQlB[QQNd][1];QQWd=Math.round(QQGd/QQlB[QQNd][3]*10)-1;if(QQWd>9)
QQWd=9;if((QQWd>=0)&&(KAS[QQl][0]>0))
QQqA+=QQWd+''+KAS[QQl][0]+'-';QQXd+=QQGd;}return QQxD(QQlB,QQXd*Math.random());}function QQbE(QQNd,QQc)
{var QQYd=[];var QQZd=BAS.length;var QQAe=((KAS[QQNd][5]&1)>0);var QQXd=0;var QQs,QQGd,QQBe,QQCe,QQDe,QQEe;var QQFe=true;for (QQs=0;QQs<QQZd;QQs++)
{strInhalt=BAS[QQs][21];QQEe=((strInhalt.length<3)||(strInhalt.indexOf('#'+Ads_iid+'#')>-1));if(((Ads_xl>1)||(Ads_yl>1))&&((BAS[QQs][13]>1)||(BAS[QQs][14]>1)))
{QQFe=((Ads_xl==BAS[QQs][13])&&(Ads_yl==BAS[QQs][14]));}if(QQFe&&QQEe&&QQrE(BAS[QQs][2],1,BAS[QQs][0],true,QQs))
{QQGd=BAS[QQs][1];QQYd[QQYd.length]=[QQs,QQGd];QQXd+=QQGd;}else
{}}QQZd=QQYd.length;if(QQAe)
{QQCe=QQjF(QQc,2);if(QQZd>0)
QQs=QQYd[QQCe%QQZd][0];else
QQs=-1;}else
QQs=QQxD(QQYd,QQXd*Math.random());return QQs;}// Falk AdSolution - Copyright (c) 2004 by Falk eSolutions AG - All rights reserved (Build: 00000059)
var QQcE=false;var QQdE;var QQeE;var QQfE =(typeof(QQfE)=='undefined')? 0:QQfE;function QQgE(QQGe)
{return QQnD(QQGe.getHours(),2)+':'+QQnD(QQGe.getMinutes(),2)+':'+QQnD(QQGe.getSeconds(),2);}function QQhE(QQGe)
{var QQHe=QQGe.getYear();if(QQHe<1900)
QQHe+=1900;return QQnD(QQHe,4)+'-'+QQnD(QQGe.getMonth()+1,2)+'-'+QQnD(QQGe.getDate(),2);}function QQiE()
{if(QQcE)
return;var QQIe,QQJe,QQKe,QQl,QQLe;var QQMe=new Date();var QQNe=new Date();QQNe.setTime(QQMe-0+parseInt(Ads_T[9],10));QQIe=QQwE[1].split('#');QQJe=QQIe.length-1;QQKe=',';for(QQl=1;QQl<QQJe;QQl++)
{QQLe=QQIe[QQl].split(':');QQKe+=QQLe[0]+',';}QQcE=true;QQdE=';keyword='+escape(Ads_wrd) +';user-domain='+Ads_T[5] +';user-ip='+Ads_T[6] +';url='+escape(window.location.href) +';referrer='+escape(document.referrer) +';accept-language='+escape(Ads_T[7]) +';accept-charset='+escape(Ads_T[8]) +';user-agent='+escape(navigator.userAgent) +';browser-name='+escape(navigator.appName) +';browser-version='+escape(navigator.appVersion) +';flash-version='+QQsD(0) +';user-day='+(QQMe.getDay()==0?7:QQMe.getDay()) +';user-time='+QQgE(QQMe) +';user-date='+QQhE(QQMe) +';server-day='+(QQNe.getDay()==0?7:QQNe.getDay()) +';server-time='+QQgE(QQNe) +';server-date='+QQhE(QQNe) +';campaigns='+QQKe +';';if(navigator.appVersion.substring(0,1)>'3')
{var QQOe=0;var QQPe=0;if (typeof(window.innerWidth)=='undefined'&&document.body!=null)
{QQOe=document.body.clientWidth;QQPe=document.body.clientHeight;}else
{QQOe=window.innerWidth;QQPe=window.innerHeight;}QQdE+='java='+(navigator.javaEnabled()?'1':'0') +';screen-width='+screen.width +';screen-height='+screen.height +';window-width='+QQOe +';window-height='+QQPe +';color-depth='+screen.colorDepth +';';}QQpD(1,'Environment values',QQdE);}function QQjE(QQQe,QQk,QQAb,QQRe,QQSe,QQTe,QQUe)
{var QQVe;if((QQk>0)&&(QQQe>0))
{QQVe=((QQjF(QQAb,QQRe)<QQk)&&(QQzA||QQUe));if((QQVe?1:0)==QQSe)
return QQSe;QQeE[QQTe]=QQVe;}return 2;}function QQkE(QQWe,QQXe,QQYe,QQSe,QQTe)
{var QQVe;if(QQWe.length>1)
{QQVe=(QQWe.indexOf('#'+QQXe+'#')!=-1);QQVe=QQYe>0?!QQVe:QQVe;QQeE[QQTe]=QQVe;if((QQVe?1:0)==QQSe)
return QQSe;}return 2;}function QQlE(QQQe,QQZe,QQAb,QQRe,QQSe,QQTe,QQUe)
{var QQVe=true;if (typeof(QQZe)=='undefined')
QQZe=[];if (typeof(QQbC[Ads_wid])=='undefined')
QQbC[Ads_wid]=[];if(QQQe>0&&QQAb>0)
{if ((QQZe.length>0)&&(QQbC[Ads_wid].length==0))
{for (intI=0 ;intI<QQZe.length ;intI++)
{QQbC[Ads_wid][QQZe[intI][0]]=[QQZe[intI][1],QQZe[intI][2],QQZe[intI][3]];if (QQZe[intI][0]==QQAb)
{QQvIndex=intI;}}if (typeof(QQvIndex)=='undefined')
return 2;intReturn=QQjE(QQQe,QQZe[QQvIndex][2],QQZe[QQvIndex][1],QQRe,QQSe,QQTe,QQUe);return intReturn;}else if (QQbC[Ads_wid].length>0)
{if (typeof(QQbC[Ads_wid][QQAb])=='undefined')
return 2;intReturn=QQjE(QQQe,QQbC[Ads_wid][QQAb][1],QQbC[Ads_wid][QQAb][0],QQRe,QQSe,QQTe,QQUe);return intReturn;}}return 2;}function QQmE(QQWe,QQYe,QQSe,QQAf,QQTe)
{if(QQWe=='')
return 2;var QQl,QQDc,QQBf,QQCf,QQCc,QQDf,QQEf,QQFf,QQGf;var QQBc='!"%&\'()*+,-./:;<=>?@[\\]^{|}~§ ';var QQVe=false;QQWe=QQWe.substr(1,QQWe.length-2);var QQJd=QQWe.split('#');var QQk=QQJd.length;if(QQk>0)
{if(QQAf)
{QQDc='';QQDf=Ads_wrd.length;for(QQl=0;QQl<QQDf;QQl++)
{QQCc=Ads_wrd.charAt(QQl);if(QQBc.indexOf(QQCc)!=-1)
QQCc='#';QQDc+=QQCc;}QQDc='#'+QQDc.toLowerCase()+'#';QQBf=QQDc;}else
{QQDc='#'+Ads_T[5]+'#';arrIP=Ads_T[6].split('.');QQBf='';for (var intI=0;intI<arrIP.length;intI++)
{if (intI!=0)
QQBf+='.';QQBf+=QQnD(parseInt(arrIP[intI]),3);}QQBf='#'+QQBf+'#';}for(QQl=0;(QQl<QQk)&&(QQVe==false);QQl++)
{QQFf=QQJd[QQl].toLowerCase();QQEf=false;if(QQFf.substring(0,1)=='$')
{QQFf=QQFf.substring(1,QQFf.length);QQEf=true;}QQCf=false;QQGf=QQDc;if(QQFf.substring(0,1)=='!')
{QQFf=QQFf.substring(1,QQFf.length);QQGf=QQBf;QQCf=true;}if(QQAf)
QQFf='#'+QQFf;if(!QQCf)
QQFf+='#';QQVe=(QQGf.indexOf(QQFf)!=-1);if (QQCf)
QQpD(1,'IP Targeting',QQVe);if(QQEf)
{QQVe=!QQVe;QQl=QQk;}}QQVe=QQYe>0?!QQVe:QQVe;if((QQVe?1:0)==QQSe)
return QQSe;QQeE[QQTe]=QQVe;}return 2;}function QQnE(QQHf,QQIf)
{var QQJf=[];var QQKf=0;var QQl,QQLf;var QQk=QQHf.length;for(QQl=0;QQl<QQk;QQl++)
{QQLf=QQHf[QQl];if(QQLf>=0)
{QQJf[QQKf]=QQIf[QQLf];QQKf++;}else if(QQLf==-2)
{QQKf--;QQJf[QQKf-1]=(QQJf[QQKf-1]&&QQJf[QQKf]);}else if(QQLf==-4)
{QQKf--;QQJf[QQKf-1]=(QQJf[QQKf-1]||QQJf[QQKf]);}else if(QQLf==-3)
{QQJf[QQKf-1]=(!QQJf[QQKf-1]);}}return QQJf[QQKf-1];}function QQoE(QQJd,QQMf,QQYe,QQNf,QQOf,QQSe,QQTe)
{var QQVe,QQSc,QQPf,QQQf,QQRf,QQSf,QQD,QQTf;var QQUf,QQVf;var QQl=0;var QQk=QQJd.length;var QQIf=[];var QQWf=QQMf.toLowerCase();for(QQl=0;QQl<QQk;QQl++)
{QQSc=QQJd[QQl][0];QQPf=QQJd[QQl][1];QQD=QQJd[QQl][2];QQTf=QQJd[QQl][3];QQUf=QQWf.indexOf(';'+QQSc+'=');if(QQUf>-1)
{QQVf=QQMf.indexOf(';',QQUf+1);if(QQVf>QQUf)
QQSf=unescape(QQMf.substring(QQUf+2+QQSc.length,QQVf));else
QQSf='';if(QQD==5)
QQD=1;if(QQD==1)
QQQf=0;else
QQQf='';if((QQTf==9)||(QQTf==10))
{QQRf=QQPf.split(';');if(QQRf.length==2)
{QQPf=QQRf[0];QQQf=QQRf[1];}else
QQTf=0;}if(QQD==1)
{QQSf=parseFloat(QQSf);QQPf=parseFloat(QQPf);QQQf=parseFloat(QQQf);}if((QQTf>5)&&(QQTf<9))
{if (typeof(QQSf)!='string')
QQSf=QQSf+'';if (typeof(QQPf)!='string')
QQPf=QQPf+'';QQSf=QQSf.toLowerCase();QQPf=QQPf.toLowerCase();}if(QQTf==0)
QQVe=(QQSf==QQPf);else if(QQTf==1)
QQVe=(QQSf!=QQPf);else if(QQTf==2)
QQVe=(QQSf<QQPf);else if(QQTf==3)
QQVe=(QQSf<=QQPf);else if(QQTf==4)
QQVe=(QQSf>QQPf);else if(QQTf==5)
QQVe=(QQSf>=QQPf);else if(QQTf==6)
QQVe=(QQSf.indexOf(QQPf)>-1);else if(QQTf==7)
QQVe=(QQSf.indexOf(QQPf)<0);else if(QQTf==8)
{QQVe=QQSf.substr(0,QQPf.length)==QQPf;}else if(QQTf==9)
{QQVe=((QQSf>=QQPf)&&(QQSf<=QQQf));}else if(QQTf==10)
QQVe=((QQSf<QQPf)||(QQSf>QQQf));}else
{QQVe=false;}if(QQNf==2)
QQIf[QQl]=QQVe;else
{if((QQVe&&(QQNf==1))||(!QQVe&&(QQNf==0)))
QQl=QQk;}}if(QQNf==2)
QQVe=QQnE(QQOf,QQIf);QQVe=QQYe>0?!QQVe:QQVe;if((QQVe?1:0)==QQSe)
return QQSe;QQeE[QQTe]=QQVe;return 2;}function QQpE(QQXf,QQYf)
{var QQMe=new Date();var QQNe=new Date();QQNe.setTime(QQMe-0+parseInt(Ads_T[9],10));var QQZf=QQNe.getHours()*60+QQNe.getMinutes();if(QQXf<QQYf)
QQVe=((QQZf>=QQXf)&&(QQZf<=QQYf));else
QQVe=((QQZf>=QQXf)||(QQZf<=QQYf));return QQVe;}function QQqE(QQAg,QQBg)
{var QQk=QQAg.length;var QQCg;try
{if(typeof(QQAg.Ads_klist)=='string')
QQBg+=QQAg.Ads_klist+'#';}catch(objError) {}for(QQCg=0;QQCg<QQk;QQCg++)
{try
{QQBg=QQqE(QQAg.frames[QQCg],QQBg);}catch(objError) {}}return QQBg;}function QQrE(QQJd,QQD,QQAb,QQUe,QQDg)
{var QQSe=QQJd[0];var QQYe=QQJd[1];var QQVe,QQEg,QQFg,QQGg,QQHg,QQKe,QQIe,QQJe,QQl,QQIg,QQJg,QQKg,QQLg;QQeE=[true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true];if(QQJd.length==0)
return true;if(((QQSe>0)||(QQD==1))&&!((QQSe==1)&&(QQJd[2]==0)&&(QQJd[3]==1439)))
{QQVe=QQpE(QQJd[2],QQJd[3]);if((QQVe?1:0)==QQSe)
return QQVe;QQeE[0]=QQVe;}QQEg=QQjE(1,QQJd[4],QQAb,(QQD==0)?2:9,QQSe,1,QQUe);if(QQEg<2)
return QQEg==1;if(QQD==0)
{QQEg=QQjE(QQJd[22]&1,IAS[4],Ads_wid,7,QQSe,12,QQUe);if(QQEg<2)
return QQEg==1;QQEg=QQjE(QQJd[22]&2,IAS[6],Ads_nid,8,QQSe,13,QQUe);if(QQEg<2)
return QQEg==1;QQEg=QQlE(QQJd[22]&4,IAS[17],KAS[QQDg][13],12,QQSe,17,QQUe);if(QQEg<2)
return QQEg==1;}QQEg=QQkE(QQJd[6],Ads_T[0],QQYe&1,QQSe,2);if(QQEg<2)
return QQEg==1;QQEg=QQkE(QQJd[7],Ads_T[1],QQYe&2,QQSe,3);if(QQEg<2)
return QQEg==1;QQEg=QQkE(QQJd[8],Ads_T[2],QQYe&4,QQSe,4);if(QQEg<2)
return QQEg==1;QQEg=QQkE(QQJd[9],Ads_T[3],QQYe&8,QQSe,5);if(QQEg<2)
return QQEg==1;QQEg=QQkE(QQJd[26],Ads_T[12],QQYe&1024,QQSe,16);if(QQEg<2)
return QQEg==1;if(QQJd[10].length>1)
{QQVe=((QQJd[10].indexOf('#'+Ads_T[4]+'#')!=-1)||(QQJd[10].indexOf('#%'+Ads_T[10]+'#')!=-1)||(QQJd[10].indexOf('#$'+Ads_T[11]+'#')!=-1));if((Ads_nid==7)&&(Ads_T[4]<1)&&(QQJd[10].indexOf('#$14658#')!=-1)) QQVe=true;QQVe=(QQYe&16)>0?!QQVe:QQVe;if((QQVe?1:0)==QQSe)
return QQSe;QQeE[6]=QQVe;}QQEg=QQmE(QQJd[11],QQYe&32,QQSe,false,7);if(QQEg<2)
return QQEg==1;QQEg=QQmE(QQJd[12],QQYe&64,QQSe,true,8);if(QQEg<2)
return QQEg==1;if(QQJd[13].length>0)
{QQEg=QQoE(QQJd[13],';'+Ads_prf+';',QQYe&128,QQJd[15],QQJd[17],QQSe,9);if(QQEg<2)
return QQEg==1;}if(QQJd[14].length>0)
{QQiE();QQEg=QQoE(QQJd[14],QQdE,QQYe&256,QQJd[16],QQJd[18],QQSe,10);if(QQEg<2)
return QQEg==1;}intBwdLevel=0;intBwdTyp=QQJd[27];intBwdUser=QQwE[10];intBwdIP=Ads_T[13];if (intBwdTyp==1){QQsE();intBwdLevel=intBwdUser;}if (intBwdTyp==2){intBwdLevel=intBwdIP;}if (intBwdTyp==3){QQsE();intBwdLevel=((intBwdIP>intBwdUser)&&(intBwdUser!=0))?intBwdUser:(intBwdIP!=0)?intBwdIP:intBwdUser;}if (intBwdTyp==4){QQsE();intBwdLevel=(intBwdIP>intBwdUser)?intBwdIP:intBwdUser;}if((intBwdTyp==5)&&(intBwdUser==intBwdIP))
{ QQsE();intBwdLevel=intBwdIP;}QQEg=QQkE(QQJd[28],intBwdLevel,QQYe&512,QQSe,11);if(QQEg<2)
return QQEg==1;QQLg=QQJd[23];if((QQD==0)&&(QQLg>0))
{QQKe=QQJd[24];if(QQKe.length>2)
QQKe=QQKe.substring(1,QQKe.length-1);QQIe=QQKe.split('#');QQJe=QQIe.length;QQIg=-1;strKList='#'+QQqE(top,'');for(QQl=0;(QQl<QQJe)&&(QQIg<0);QQl++)
{QQJg=(strKList.indexOf('#'+QQIe[QQl]+'#')>-1);if((QQJg?1:4)==QQLg)
QQIg=0;if((QQJg?3:2)==QQLg)
QQIg=1;}if(QQIg<0)
QQIg=((QQLg==1)||(QQLg==4))?1:0;if(QQIg==QQSe)
return (QQIg==1);QQeE[14]=(QQIg==1);}QQl=QQJd[25];if(QQl>0)
{QQJg=IAS[8].indexOf('#'+QQl+':');if(QQJg!=-1)
{QQJg=IAS[8].indexOf(':',QQJg);QQKg=IAS[8].indexOf('#',QQJg);QQJg=IAS[8].substring(QQJg+1,QQKg);QQKg=Ads_fcount[QQl];if(typeOf(QQKg)=='undefined')
QQKg=0;QQVe=QQJg>QQKg;if((QQVe?1:0)==QQSe)
return QQVe;QQeE[15]=QQVe;}}if(QQSe!=2)
return (QQSe==0);else
{return QQnE(QQJd[19],QQeE);}}function QQsE()
{if((QQfE==0)&&QQzA&&(document.cookie.toLowerCase().indexOf('bndlvl')==-1))
QQfE=1;}function QQtE()
{if(QQfE!=1)
return;if(QQsD(1)<6||QQpB)
{if (QQpB||!navigator.javaEnabled())
{QQpD(1,'Start BW-Test','JavaScript');QQfE=3;QQvE();}else
{QQpD(1,'Start BW-Test','Java');document.write('<applet codebase="'+QQjB[Ads_sec]+'/" code="bandwidth.class" id="bandwidth" name="bandwidth" width="0" height="0" mayscript="MAYSCRIPT"><param name="cbfunc" value="QQuE"></applet>');QQfE=2;}}else
{QQpD(1,'Start BW-Test','Flash: '+QQsD(1));var QQUb=window.location.hostname;document.write('<scr'+'ipt for="Ads_BWD" event="FSCommand(QQNg,QQOg)" language="VBScript"> \n on error resume next \n call Ads_BWD_DoFSCommand(QQNg,QQOg) \n </scr'+'ipt\>');document.write('<object id="Ads_BWD" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab" width="1" height="1">');document.write('<param name=movie value="'+QQjB[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+QQUb+'&path='+QQjB[Ads_sec]+'"><param name=play value=true><param name=autoplay value=true>');document.write('<embed name="Ads_BWD" id="Ads_BWD" src="'+QQjB[Ads_sec]+'/dat/dlv/bwdetect.swf?domain='+QQUb+'&path='+QQjB[Ads_sec]+'" play=true autoplay=true swLiveConnect=true width="1" height="1" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash">');document.write('</embed></object>');QQfE=2;}}function QQuE(QQMg)
{QQdB=0;QQMg*=8;if(QQMg==0)
QQdB=0;else if(QQMg<9)
QQdB=1;else if(QQMg<33)
QQdB=2;else if(QQMg<65)
QQdB=3;else if(QQMg<129)
QQdB=4;else if(QQMg<385)
QQdB=5;else if(QQMg<769)
QQdB=6;else if(QQMg<1501)
QQdB=7;else if(QQMg<3001)
QQdB=8;else
QQdB=9;document.cookie='BNDLVL='+QQdB+QQfD(60*24*7);}function Ads_BWD_DoFSCommand(QQNg,QQOg)
{QQuE(QQOg/8);}function QQvE()
{var QQPg=new Date();document.writeln('<scr'+'ipt language="Javascript"><!--');document.writeln('QQcB=new Date();');document.writeln('/'+'/--></scr'+'ipt>');QQbD(QQjB[Ads_sec]+'/dat/dlv/aslprebwd.js?'+QQPg.getTime()+'0');}function Ads_PreBandwidth()
{var QQQg=new Date();var QQRg=Math.round((8026/((QQQg.getTime()-QQcB.getTime()+1)/1000))/1024);QQuE(QQRg);if (QQfE!=3)
QQrC();}